import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Vardan Pal | Website & Cloud Technology Specialist | NIT Srinagar",
  description: "Final year B.Tech student in Information Technology at NIT Srinagar, specializing in Website Development & Cloud Technology. Expert in building full-stack web applications with animated interfaces, scalable backends, and cloud deployments. Previously worked at Novetiq Umbrella on cloud-based solutions.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Vardan Pal",
    url: "https://github.com/vardxn",
  },
} as const;
