import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Vardan Pal | Full-Stack Web Developer | NIT Srinagar",
  description: "Final year B.Tech student in Information Technology at NIT Srinagar. Full-Stack Web Developer specializing in animated frontends, backend APIs, databases, and cloud hosting. Previously worked at Novetiq Umbrella. Expert in building production-ready web applications and Business SaaS platforms.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Vardan Pal",
    url: "https://github.com/vardxn",
  },
} as const;
